// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/workspace.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiWorkspaceInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -217916187;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'maicenta_bridge',
        ioDirectory: '../../core/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWorkspaceCreateLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String displayName,
  });

  Future<void> crateApiWorkspaceDeleteLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String fallbackMailboxId,
  });

  Future<WorkspaceSnapshot> crateApiWorkspaceDeleteMailAccount({
    required String databasePath,
    required String accountId,
  });

  Future<void> crateApiWorkspaceExportAttachment({
    required String databasePath,
    required String attachmentId,
    required String destinationPath,
  });

  Future<void> crateApiWorkspaceExportProfile({
    required String databasePath,
    required String destinationPath,
    required String password,
  });

  Future<WorkspaceSnapshot> crateApiWorkspaceImportProfile({
    required String databasePath,
    required String sourcePath,
    required String password,
  });

  Future<void> crateApiWorkspaceInitApp();

  Future<List<MessageDto>> crateApiWorkspaceLoadMailboxMessages({
    required String databasePath,
    required String mailboxId,
    required int offset,
    required int limit,
  });

  Future<MessageDto?> crateApiWorkspaceLoadRemoteMessageContent({
    required String databasePath,
    required String messageId,
  });

  Future<WorkspaceSnapshot> crateApiWorkspaceOpenWorkspace({
    required String databasePath,
  });

  Future<void> crateApiWorkspaceRenameLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String displayName,
  });

  Future<void> crateApiWorkspaceSaveDarkMode({
    required String databasePath,
    required bool enabled,
  });

  Future<void> crateApiWorkspaceSaveFavoriteMailboxes({
    required String databasePath,
    required List<String> mailboxIds,
  });

  Future<void> crateApiWorkspaceSaveLocalCalendarEvent({
    required String databasePath,
    required LocalCalendarEventInput input,
  });

  Future<void> crateApiWorkspaceSaveLocalContact({
    required String databasePath,
    required LocalContactInput input,
  });

  Future<MessageDto> crateApiWorkspaceSaveLocalMessage({
    required String databasePath,
    required LocalMessageInput input,
  });

  Future<void> crateApiWorkspaceSaveLocalTask({
    required String databasePath,
    required LocalTaskInput input,
  });

  Future<void> crateApiWorkspaceSaveMailAccount({
    required String databasePath,
    required MailAccountInput input,
    required String password,
  });

  Future<void> crateApiWorkspaceSaveOauthMailAccount({
    required String databasePath,
    required MailAccountInput input,
    required OAuthTokenInput tokens,
  });

  Future<List<MessageDto>> crateApiWorkspaceSearchProfileMessages({
    required String databasePath,
    required String query,
    required bool includeContent,
    required int limit,
  });

  Future<String> crateApiWorkspaceSendAccountMessage({
    required String databasePath,
    required OutgoingMessageInput input,
  });

  Future<DraftSyncDto> crateApiWorkspaceSynchronizeMailAccountDrafts({
    required String databasePath,
    required String accountId,
  });

  Future<WorkspaceSnapshot> crateApiWorkspaceSynchronizeMailAccounts({
    required String databasePath,
  });

  Future<void> crateApiWorkspaceTestMailAccountConnection({
    required MailAccountInput input,
    required String password,
  });

  Future<void> crateApiWorkspaceTestOauthMailAccountConnection({
    required MailAccountInput input,
    required String accessToken,
  });

  Future<int> crateApiWorkspaceUpdateLocalMessage({
    required String databasePath,
    required String messageId,
    required String mailboxId,
    required bool unread,
    required bool flagged,
  });

  Future<MailboxIdleDto> crateApiWorkspaceWaitForMailboxIdleChange({
    required String databasePath,
    required String mailboxId,
    required int timeoutSeconds,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWorkspaceCreateLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceCreateLocalMailboxConstMeta,
        argValues: [databasePath, mailboxId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceCreateLocalMailboxConstMeta =>
      const TaskConstMeta(
        debugName: "create_local_mailbox",
        argNames: ["databasePath", "mailboxId", "displayName"],
      );

  @override
  Future<void> crateApiWorkspaceDeleteLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String fallbackMailboxId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_String(fallbackMailboxId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceDeleteLocalMailboxConstMeta,
        argValues: [databasePath, mailboxId, fallbackMailboxId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceDeleteLocalMailboxConstMeta =>
      const TaskConstMeta(
        debugName: "delete_local_mailbox",
        argNames: ["databasePath", "mailboxId", "fallbackMailboxId"],
      );

  @override
  Future<WorkspaceSnapshot> crateApiWorkspaceDeleteMailAccount({
    required String databasePath,
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(accountId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceDeleteMailAccountConstMeta,
        argValues: [databasePath, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceDeleteMailAccountConstMeta =>
      const TaskConstMeta(
        debugName: "delete_mail_account",
        argNames: ["databasePath", "accountId"],
      );

  @override
  Future<void> crateApiWorkspaceExportAttachment({
    required String databasePath,
    required String attachmentId,
    required String destinationPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(attachmentId, serializer);
          sse_encode_String(destinationPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceExportAttachmentConstMeta,
        argValues: [databasePath, attachmentId, destinationPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceExportAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "export_attachment",
        argNames: ["databasePath", "attachmentId", "destinationPath"],
      );

  @override
  Future<void> crateApiWorkspaceExportProfile({
    required String databasePath,
    required String destinationPath,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(destinationPath, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceExportProfileConstMeta,
        argValues: [databasePath, destinationPath, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceExportProfileConstMeta =>
      const TaskConstMeta(
        debugName: "export_profile",
        argNames: ["databasePath", "destinationPath", "password"],
      );

  @override
  Future<WorkspaceSnapshot> crateApiWorkspaceImportProfile({
    required String databasePath,
    required String sourcePath,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(sourcePath, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceImportProfileConstMeta,
        argValues: [databasePath, sourcePath, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceImportProfileConstMeta =>
      const TaskConstMeta(
        debugName: "import_profile",
        argNames: ["databasePath", "sourcePath", "password"],
      );

  @override
  Future<void> crateApiWorkspaceInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<MessageDto>> crateApiWorkspaceLoadMailboxMessages({
    required String databasePath,
    required String mailboxId,
    required int offset,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceLoadMailboxMessagesConstMeta,
        argValues: [databasePath, mailboxId, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceLoadMailboxMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "load_mailbox_messages",
        argNames: ["databasePath", "mailboxId", "offset", "limit"],
      );

  @override
  Future<MessageDto?> crateApiWorkspaceLoadRemoteMessageContent({
    required String databasePath,
    required String messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(messageId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceLoadRemoteMessageContentConstMeta,
        argValues: [databasePath, messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceLoadRemoteMessageContentConstMeta =>
      const TaskConstMeta(
        debugName: "load_remote_message_content",
        argNames: ["databasePath", "messageId"],
      );

  @override
  Future<WorkspaceSnapshot> crateApiWorkspaceOpenWorkspace({
    required String databasePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceOpenWorkspaceConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceOpenWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "open_workspace",
        argNames: ["databasePath"],
      );

  @override
  Future<void> crateApiWorkspaceRenameLocalMailbox({
    required String databasePath,
    required String mailboxId,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceRenameLocalMailboxConstMeta,
        argValues: [databasePath, mailboxId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceRenameLocalMailboxConstMeta =>
      const TaskConstMeta(
        debugName: "rename_local_mailbox",
        argNames: ["databasePath", "mailboxId", "displayName"],
      );

  @override
  Future<void> crateApiWorkspaceSaveDarkMode({
    required String databasePath,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveDarkModeConstMeta,
        argValues: [databasePath, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveDarkModeConstMeta =>
      const TaskConstMeta(
        debugName: "save_dark_mode",
        argNames: ["databasePath", "enabled"],
      );

  @override
  Future<void> crateApiWorkspaceSaveFavoriteMailboxes({
    required String databasePath,
    required List<String> mailboxIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_list_String(mailboxIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveFavoriteMailboxesConstMeta,
        argValues: [databasePath, mailboxIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveFavoriteMailboxesConstMeta =>
      const TaskConstMeta(
        debugName: "save_favorite_mailboxes",
        argNames: ["databasePath", "mailboxIds"],
      );

  @override
  Future<void> crateApiWorkspaceSaveLocalCalendarEvent({
    required String databasePath,
    required LocalCalendarEventInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_local_calendar_event_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveLocalCalendarEventConstMeta,
        argValues: [databasePath, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveLocalCalendarEventConstMeta =>
      const TaskConstMeta(
        debugName: "save_local_calendar_event",
        argNames: ["databasePath", "input"],
      );

  @override
  Future<void> crateApiWorkspaceSaveLocalContact({
    required String databasePath,
    required LocalContactInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_local_contact_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveLocalContactConstMeta,
        argValues: [databasePath, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveLocalContactConstMeta =>
      const TaskConstMeta(
        debugName: "save_local_contact",
        argNames: ["databasePath", "input"],
      );

  @override
  Future<MessageDto> crateApiWorkspaceSaveLocalMessage({
    required String databasePath,
    required LocalMessageInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_local_message_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveLocalMessageConstMeta,
        argValues: [databasePath, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveLocalMessageConstMeta =>
      const TaskConstMeta(
        debugName: "save_local_message",
        argNames: ["databasePath", "input"],
      );

  @override
  Future<void> crateApiWorkspaceSaveLocalTask({
    required String databasePath,
    required LocalTaskInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_local_task_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveLocalTaskConstMeta,
        argValues: [databasePath, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveLocalTaskConstMeta =>
      const TaskConstMeta(
        debugName: "save_local_task",
        argNames: ["databasePath", "input"],
      );

  @override
  Future<void> crateApiWorkspaceSaveMailAccount({
    required String databasePath,
    required MailAccountInput input,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_mail_account_input(input, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveMailAccountConstMeta,
        argValues: [databasePath, input, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveMailAccountConstMeta =>
      const TaskConstMeta(
        debugName: "save_mail_account",
        argNames: ["databasePath", "input", "password"],
      );

  @override
  Future<void> crateApiWorkspaceSaveOauthMailAccount({
    required String databasePath,
    required MailAccountInput input,
    required OAuthTokenInput tokens,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_mail_account_input(input, serializer);
          sse_encode_box_autoadd_o_auth_token_input(tokens, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSaveOauthMailAccountConstMeta,
        argValues: [databasePath, input, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSaveOauthMailAccountConstMeta =>
      const TaskConstMeta(
        debugName: "save_oauth_mail_account",
        argNames: ["databasePath", "input", "tokens"],
      );

  @override
  Future<List<MessageDto>> crateApiWorkspaceSearchProfileMessages({
    required String databasePath,
    required String query,
    required bool includeContent,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(query, serializer);
          sse_encode_bool(includeContent, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSearchProfileMessagesConstMeta,
        argValues: [databasePath, query, includeContent, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSearchProfileMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "search_profile_messages",
        argNames: ["databasePath", "query", "includeContent", "limit"],
      );

  @override
  Future<String> crateApiWorkspaceSendAccountMessage({
    required String databasePath,
    required OutgoingMessageInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_box_autoadd_outgoing_message_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSendAccountMessageConstMeta,
        argValues: [databasePath, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSendAccountMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_account_message",
        argNames: ["databasePath", "input"],
      );

  @override
  Future<DraftSyncDto> crateApiWorkspaceSynchronizeMailAccountDrafts({
    required String databasePath,
    required String accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(accountId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_draft_sync_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSynchronizeMailAccountDraftsConstMeta,
        argValues: [databasePath, accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSynchronizeMailAccountDraftsConstMeta =>
      const TaskConstMeta(
        debugName: "synchronize_mail_account_drafts",
        argNames: ["databasePath", "accountId"],
      );

  @override
  Future<WorkspaceSnapshot> crateApiWorkspaceSynchronizeMailAccounts({
    required String databasePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceSynchronizeMailAccountsConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceSynchronizeMailAccountsConstMeta =>
      const TaskConstMeta(
        debugName: "synchronize_mail_accounts",
        argNames: ["databasePath"],
      );

  @override
  Future<void> crateApiWorkspaceTestMailAccountConnection({
    required MailAccountInput input,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mail_account_input(input, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceTestMailAccountConnectionConstMeta,
        argValues: [input, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceTestMailAccountConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_mail_account_connection",
        argNames: ["input", "password"],
      );

  @override
  Future<void> crateApiWorkspaceTestOauthMailAccountConnection({
    required MailAccountInput input,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mail_account_input(input, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceTestOauthMailAccountConnectionConstMeta,
        argValues: [input, accessToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceTestOauthMailAccountConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "test_oauth_mail_account_connection",
        argNames: ["input", "accessToken"],
      );

  @override
  Future<int> crateApiWorkspaceUpdateLocalMessage({
    required String databasePath,
    required String messageId,
    required String mailboxId,
    required bool unread,
    required bool flagged,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(messageId, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_bool(unread, serializer);
          sse_encode_bool(flagged, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceUpdateLocalMessageConstMeta,
        argValues: [databasePath, messageId, mailboxId, unread, flagged],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceUpdateLocalMessageConstMeta =>
      const TaskConstMeta(
        debugName: "update_local_message",
        argNames: [
          "databasePath",
          "messageId",
          "mailboxId",
          "unread",
          "flagged",
        ],
      );

  @override
  Future<MailboxIdleDto> crateApiWorkspaceWaitForMailboxIdleChange({
    required String databasePath,
    required String mailboxId,
    required int timeoutSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          sse_encode_String(mailboxId, serializer);
          sse_encode_u_32(timeoutSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mailbox_idle_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWorkspaceWaitForMailboxIdleChangeConstMeta,
        argValues: [databasePath, mailboxId, timeoutSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceWaitForMailboxIdleChangeConstMeta =>
      const TaskConstMeta(
        debugName: "wait_for_mailbox_idle_change",
        argNames: ["databasePath", "mailboxId", "timeoutSeconds"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  LocalCalendarEventInput dco_decode_box_autoadd_local_calendar_event_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_calendar_event_input(raw);
  }

  @protected
  LocalContactInput dco_decode_box_autoadd_local_contact_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_contact_input(raw);
  }

  @protected
  LocalMessageInput dco_decode_box_autoadd_local_message_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_message_input(raw);
  }

  @protected
  LocalTaskInput dco_decode_box_autoadd_local_task_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_task_input(raw);
  }

  @protected
  MailAccountInput dco_decode_box_autoadd_mail_account_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mail_account_input(raw);
  }

  @protected
  MessageDto dco_decode_box_autoadd_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message_dto(raw);
  }

  @protected
  OAuthTokenInput dco_decode_box_autoadd_o_auth_token_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_o_auth_token_input(raw);
  }

  @protected
  OutgoingMessageInput dco_decode_box_autoadd_outgoing_message_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_outgoing_message_input(raw);
  }

  @protected
  CalendarEventDto dco_decode_calendar_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CalendarEventDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      startsAtMs: dco_decode_i_64(arr[2]),
      endsAtMs: dco_decode_i_64(arr[3]),
      location: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  ContactDto dco_decode_contact_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ContactDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
    );
  }

  @protected
  DraftSyncDto dco_decode_draft_sync_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DraftSyncDto(
      synchronized: dco_decode_u_32(arr[0]),
      pending: dco_decode_u_32(arr[1]),
      warnings: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CalendarEventDto> dco_decode_list_calendar_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_calendar_event_dto).toList();
  }

  @protected
  List<ContactDto> dco_decode_list_contact_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_contact_dto).toList();
  }

  @protected
  List<MailAccountDto> dco_decode_list_mail_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mail_account_dto).toList();
  }

  @protected
  List<MailboxDto> dco_decode_list_mailbox_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mailbox_dto).toList();
  }

  @protected
  List<MessageAttachmentDto> dco_decode_list_message_attachment_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_message_attachment_dto)
        .toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskDto> dco_decode_list_task_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_dto).toList();
  }

  @protected
  LocalCalendarEventInput dco_decode_local_calendar_event_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LocalCalendarEventInput(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      startsAtMs: dco_decode_i_64(arr[2]),
      endsAtMs: dco_decode_i_64(arr[3]),
      location: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  LocalContactInput dco_decode_local_contact_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LocalContactInput(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
    );
  }

  @protected
  LocalMessageInput dco_decode_local_message_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 20)
      throw Exception('unexpected arr length: expect 20 but see ${arr.length}');
    return LocalMessageInput(
      id: dco_decode_String(arr[0]),
      accountId: dco_decode_String(arr[1]),
      mailboxId: dco_decode_String(arr[2]),
      sender: dco_decode_String(arr[3]),
      email: dco_decode_String(arr[4]),
      subject: dco_decode_String(arr[5]),
      preview: dco_decode_String(arr[6]),
      plainText: dco_decode_String(arr[7]),
      htmlText: dco_decode_String(arr[8]),
      attachmentPaths: dco_decode_list_String(arr[9]),
      retainedAttachmentIds: dco_decode_list_String(arr[10]),
      draftTo: dco_decode_String(arr[11]),
      draftCc: dco_decode_String(arr[12]),
      draftBcc: dco_decode_String(arr[13]),
      editorDeltaJson: dco_decode_String(arr[14]),
      receivedAtMs: dco_decode_i_64(arr[15]),
      unread: dco_decode_bool(arr[16]),
      flagged: dco_decode_bool(arr[17]),
      draft: dco_decode_bool(arr[18]),
      hasAttachment: dco_decode_bool(arr[19]),
    );
  }

  @protected
  LocalTaskInput dco_decode_local_task_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LocalTaskInput(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      dueAtMs: dco_decode_opt_box_autoadd_i_64(arr[2]),
      completed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  MailAccountDto dco_decode_mail_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return MailAccountDto(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
      imapHost: dco_decode_String(arr[3]),
      imapPort: dco_decode_u_16(arr[4]),
      imapSecurity: dco_decode_String(arr[5]),
      imapUsername: dco_decode_String(arr[6]),
      smtpHost: dco_decode_String(arr[7]),
      smtpPort: dco_decode_u_16(arr[8]),
      smtpSecurity: dco_decode_String(arr[9]),
      smtpUsername: dco_decode_String(arr[10]),
      authentication: dco_decode_String(arr[11]),
      oauthProvider: dco_decode_opt_String(arr[12]),
      lastSyncAtMs: dco_decode_opt_box_autoadd_i_64(arr[13]),
    );
  }

  @protected
  MailAccountInput dco_decode_mail_account_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MailAccountInput(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
      imapHost: dco_decode_String(arr[3]),
      imapPort: dco_decode_u_16(arr[4]),
      imapSecurity: dco_decode_String(arr[5]),
      imapUsername: dco_decode_String(arr[6]),
      smtpHost: dco_decode_String(arr[7]),
      smtpPort: dco_decode_u_16(arr[8]),
      smtpSecurity: dco_decode_String(arr[9]),
      smtpUsername: dco_decode_String(arr[10]),
    );
  }

  @protected
  MailboxDto dco_decode_mailbox_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MailboxDto(
      id: dco_decode_String(arr[0]),
      accountId: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      role: dco_decode_String(arr[3]),
      unreadCount: dco_decode_u_32(arr[4]),
      totalCount: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  MailboxIdleDto dco_decode_mailbox_idle_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MailboxIdleDto(
      idleSupported: dco_decode_bool(arr[0]),
      changed: dco_decode_bool(arr[1]),
    );
  }

  @protected
  MessageAttachmentDto dco_decode_message_attachment_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MessageAttachmentDto(
      id: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      contentType: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_32(arr[3]),
      availableLocally: dco_decode_bool(arr[4]),
    );
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 24)
      throw Exception('unexpected arr length: expect 24 but see ${arr.length}');
    return MessageDto(
      id: dco_decode_String(arr[0]),
      accountId: dco_decode_String(arr[1]),
      mailboxId: dco_decode_String(arr[2]),
      sender: dco_decode_String(arr[3]),
      email: dco_decode_String(arr[4]),
      subject: dco_decode_String(arr[5]),
      preview: dco_decode_String(arr[6]),
      body: dco_decode_String(arr[7]),
      plainText: dco_decode_String(arr[8]),
      receivedAtMs: dco_decode_i_64(arr[9]),
      unread: dco_decode_bool(arr[10]),
      flagged: dco_decode_bool(arr[11]),
      draft: dco_decode_bool(arr[12]),
      editableDraft: dco_decode_bool(arr[13]),
      draftSynchronized: dco_decode_bool(arr[14]),
      draftTo: dco_decode_String(arr[15]),
      draftCc: dco_decode_String(arr[16]),
      draftBcc: dco_decode_String(arr[17]),
      toRecipients: dco_decode_String(arr[18]),
      ccRecipients: dco_decode_String(arr[19]),
      bccRecipients: dco_decode_String(arr[20]),
      editorDeltaJson: dco_decode_String(arr[21]),
      hasAttachment: dco_decode_bool(arr[22]),
      attachments: dco_decode_list_message_attachment_dto(arr[23]),
    );
  }

  @protected
  OAuthTokenInput dco_decode_o_auth_token_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return OAuthTokenInput(
      provider: dco_decode_String(arr[0]),
      clientId: dco_decode_String(arr[1]),
      accessToken: dco_decode_String(arr[2]),
      refreshToken: dco_decode_String(arr[3]),
      expiresAtMs: dco_decode_i_64(arr[4]),
      tokenEndpoint: dco_decode_String(arr[5]),
      scopes: dco_decode_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  MessageDto? dco_decode_opt_box_autoadd_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_message_dto(raw);
  }

  @protected
  OutgoingMessageInput dco_decode_outgoing_message_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return OutgoingMessageInput(
      accountId: dco_decode_String(arr[0]),
      to: dco_decode_list_String(arr[1]),
      cc: dco_decode_list_String(arr[2]),
      bcc: dco_decode_list_String(arr[3]),
      subject: dco_decode_String(arr[4]),
      plainText: dco_decode_String(arr[5]),
      htmlText: dco_decode_String(arr[6]),
      attachmentPaths: dco_decode_list_String(arr[7]),
      storedAttachmentIds: dco_decode_list_String(arr[8]),
      highImportance: dco_decode_bool(arr[9]),
    );
  }

  @protected
  TaskDto dco_decode_task_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TaskDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      dueAtMs: dco_decode_opt_box_autoadd_i_64(arr[2]),
      completed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return WorkspaceSnapshot(
      mailboxes: dco_decode_list_mailbox_dto(arr[0]),
      favoriteMailboxIds: dco_decode_list_String(arr[1]),
      darkModeEnabled: dco_decode_bool(arr[2]),
      messages: dco_decode_list_message_dto(arr[3]),
      calendarEvents: dco_decode_list_calendar_event_dto(arr[4]),
      tasks: dco_decode_list_task_dto(arr[5]),
      contacts: dco_decode_list_contact_dto(arr[6]),
      mailAccounts: dco_decode_list_mail_account_dto(arr[7]),
      syncWarnings: dco_decode_list_String(arr[8]),
      catalogMessagesRemaining: dco_decode_u_32(arr[9]),
      deltaMailboxesSynchronized: dco_decode_u_32(arr[10]),
      fullMailboxesReconciled: dco_decode_u_32(arr[11]),
      qresyncMailboxesSynchronized: dco_decode_u_32(arr[12]),
      pendingMailOperations: dco_decode_u_32(arr[13]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  LocalCalendarEventInput sse_decode_box_autoadd_local_calendar_event_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_calendar_event_input(deserializer));
  }

  @protected
  LocalContactInput sse_decode_box_autoadd_local_contact_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_contact_input(deserializer));
  }

  @protected
  LocalMessageInput sse_decode_box_autoadd_local_message_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_message_input(deserializer));
  }

  @protected
  LocalTaskInput sse_decode_box_autoadd_local_task_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_task_input(deserializer));
  }

  @protected
  MailAccountInput sse_decode_box_autoadd_mail_account_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mail_account_input(deserializer));
  }

  @protected
  MessageDto sse_decode_box_autoadd_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message_dto(deserializer));
  }

  @protected
  OAuthTokenInput sse_decode_box_autoadd_o_auth_token_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_o_auth_token_input(deserializer));
  }

  @protected
  OutgoingMessageInput sse_decode_box_autoadd_outgoing_message_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_outgoing_message_input(deserializer));
  }

  @protected
  CalendarEventDto sse_decode_calendar_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_startsAtMs = sse_decode_i_64(deserializer);
    var var_endsAtMs = sse_decode_i_64(deserializer);
    var var_location = sse_decode_opt_String(deserializer);
    return CalendarEventDto(
      id: var_id,
      title: var_title,
      startsAtMs: var_startsAtMs,
      endsAtMs: var_endsAtMs,
      location: var_location,
    );
  }

  @protected
  ContactDto sse_decode_contact_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    return ContactDto(id: var_id, name: var_name, email: var_email);
  }

  @protected
  DraftSyncDto sse_decode_draft_sync_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_synchronized = sse_decode_u_32(deserializer);
    var var_pending = sse_decode_u_32(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return DraftSyncDto(
      synchronized: var_synchronized,
      pending: var_pending,
      warnings: var_warnings,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CalendarEventDto> sse_decode_list_calendar_event_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CalendarEventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_calendar_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ContactDto> sse_decode_list_contact_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContactDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_contact_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MailAccountDto> sse_decode_list_mail_account_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MailAccountDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mail_account_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MailboxDto> sse_decode_list_mailbox_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MailboxDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mailbox_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageAttachmentDto> sse_decode_list_message_attachment_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageAttachmentDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_attachment_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskDto> sse_decode_list_task_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LocalCalendarEventInput sse_decode_local_calendar_event_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_startsAtMs = sse_decode_i_64(deserializer);
    var var_endsAtMs = sse_decode_i_64(deserializer);
    var var_location = sse_decode_opt_String(deserializer);
    return LocalCalendarEventInput(
      id: var_id,
      title: var_title,
      startsAtMs: var_startsAtMs,
      endsAtMs: var_endsAtMs,
      location: var_location,
    );
  }

  @protected
  LocalContactInput sse_decode_local_contact_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    return LocalContactInput(id: var_id, name: var_name, email: var_email);
  }

  @protected
  LocalMessageInput sse_decode_local_message_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_accountId = sse_decode_String(deserializer);
    var var_mailboxId = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_preview = sse_decode_String(deserializer);
    var var_plainText = sse_decode_String(deserializer);
    var var_htmlText = sse_decode_String(deserializer);
    var var_attachmentPaths = sse_decode_list_String(deserializer);
    var var_retainedAttachmentIds = sse_decode_list_String(deserializer);
    var var_draftTo = sse_decode_String(deserializer);
    var var_draftCc = sse_decode_String(deserializer);
    var var_draftBcc = sse_decode_String(deserializer);
    var var_editorDeltaJson = sse_decode_String(deserializer);
    var var_receivedAtMs = sse_decode_i_64(deserializer);
    var var_unread = sse_decode_bool(deserializer);
    var var_flagged = sse_decode_bool(deserializer);
    var var_draft = sse_decode_bool(deserializer);
    var var_hasAttachment = sse_decode_bool(deserializer);
    return LocalMessageInput(
      id: var_id,
      accountId: var_accountId,
      mailboxId: var_mailboxId,
      sender: var_sender,
      email: var_email,
      subject: var_subject,
      preview: var_preview,
      plainText: var_plainText,
      htmlText: var_htmlText,
      attachmentPaths: var_attachmentPaths,
      retainedAttachmentIds: var_retainedAttachmentIds,
      draftTo: var_draftTo,
      draftCc: var_draftCc,
      draftBcc: var_draftBcc,
      editorDeltaJson: var_editorDeltaJson,
      receivedAtMs: var_receivedAtMs,
      unread: var_unread,
      flagged: var_flagged,
      draft: var_draft,
      hasAttachment: var_hasAttachment,
    );
  }

  @protected
  LocalTaskInput sse_decode_local_task_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_dueAtMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    return LocalTaskInput(
      id: var_id,
      title: var_title,
      dueAtMs: var_dueAtMs,
      completed: var_completed,
    );
  }

  @protected
  MailAccountDto sse_decode_mail_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_imapHost = sse_decode_String(deserializer);
    var var_imapPort = sse_decode_u_16(deserializer);
    var var_imapSecurity = sse_decode_String(deserializer);
    var var_imapUsername = sse_decode_String(deserializer);
    var var_smtpHost = sse_decode_String(deserializer);
    var var_smtpPort = sse_decode_u_16(deserializer);
    var var_smtpSecurity = sse_decode_String(deserializer);
    var var_smtpUsername = sse_decode_String(deserializer);
    var var_authentication = sse_decode_String(deserializer);
    var var_oauthProvider = sse_decode_opt_String(deserializer);
    var var_lastSyncAtMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    return MailAccountDto(
      id: var_id,
      displayName: var_displayName,
      email: var_email,
      imapHost: var_imapHost,
      imapPort: var_imapPort,
      imapSecurity: var_imapSecurity,
      imapUsername: var_imapUsername,
      smtpHost: var_smtpHost,
      smtpPort: var_smtpPort,
      smtpSecurity: var_smtpSecurity,
      smtpUsername: var_smtpUsername,
      authentication: var_authentication,
      oauthProvider: var_oauthProvider,
      lastSyncAtMs: var_lastSyncAtMs,
    );
  }

  @protected
  MailAccountInput sse_decode_mail_account_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_imapHost = sse_decode_String(deserializer);
    var var_imapPort = sse_decode_u_16(deserializer);
    var var_imapSecurity = sse_decode_String(deserializer);
    var var_imapUsername = sse_decode_String(deserializer);
    var var_smtpHost = sse_decode_String(deserializer);
    var var_smtpPort = sse_decode_u_16(deserializer);
    var var_smtpSecurity = sse_decode_String(deserializer);
    var var_smtpUsername = sse_decode_String(deserializer);
    return MailAccountInput(
      id: var_id,
      displayName: var_displayName,
      email: var_email,
      imapHost: var_imapHost,
      imapPort: var_imapPort,
      imapSecurity: var_imapSecurity,
      imapUsername: var_imapUsername,
      smtpHost: var_smtpHost,
      smtpPort: var_smtpPort,
      smtpSecurity: var_smtpSecurity,
      smtpUsername: var_smtpUsername,
    );
  }

  @protected
  MailboxDto sse_decode_mailbox_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_accountId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_unreadCount = sse_decode_u_32(deserializer);
    var var_totalCount = sse_decode_u_32(deserializer);
    return MailboxDto(
      id: var_id,
      accountId: var_accountId,
      displayName: var_displayName,
      role: var_role,
      unreadCount: var_unreadCount,
      totalCount: var_totalCount,
    );
  }

  @protected
  MailboxIdleDto sse_decode_mailbox_idle_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_idleSupported = sse_decode_bool(deserializer);
    var var_changed = sse_decode_bool(deserializer);
    return MailboxIdleDto(
      idleSupported: var_idleSupported,
      changed: var_changed,
    );
  }

  @protected
  MessageAttachmentDto sse_decode_message_attachment_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_32(deserializer);
    var var_availableLocally = sse_decode_bool(deserializer);
    return MessageAttachmentDto(
      id: var_id,
      fileName: var_fileName,
      contentType: var_contentType,
      sizeBytes: var_sizeBytes,
      availableLocally: var_availableLocally,
    );
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_accountId = sse_decode_String(deserializer);
    var var_mailboxId = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_preview = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_plainText = sse_decode_String(deserializer);
    var var_receivedAtMs = sse_decode_i_64(deserializer);
    var var_unread = sse_decode_bool(deserializer);
    var var_flagged = sse_decode_bool(deserializer);
    var var_draft = sse_decode_bool(deserializer);
    var var_editableDraft = sse_decode_bool(deserializer);
    var var_draftSynchronized = sse_decode_bool(deserializer);
    var var_draftTo = sse_decode_String(deserializer);
    var var_draftCc = sse_decode_String(deserializer);
    var var_draftBcc = sse_decode_String(deserializer);
    var var_toRecipients = sse_decode_String(deserializer);
    var var_ccRecipients = sse_decode_String(deserializer);
    var var_bccRecipients = sse_decode_String(deserializer);
    var var_editorDeltaJson = sse_decode_String(deserializer);
    var var_hasAttachment = sse_decode_bool(deserializer);
    var var_attachments = sse_decode_list_message_attachment_dto(deserializer);
    return MessageDto(
      id: var_id,
      accountId: var_accountId,
      mailboxId: var_mailboxId,
      sender: var_sender,
      email: var_email,
      subject: var_subject,
      preview: var_preview,
      body: var_body,
      plainText: var_plainText,
      receivedAtMs: var_receivedAtMs,
      unread: var_unread,
      flagged: var_flagged,
      draft: var_draft,
      editableDraft: var_editableDraft,
      draftSynchronized: var_draftSynchronized,
      draftTo: var_draftTo,
      draftCc: var_draftCc,
      draftBcc: var_draftBcc,
      toRecipients: var_toRecipients,
      ccRecipients: var_ccRecipients,
      bccRecipients: var_bccRecipients,
      editorDeltaJson: var_editorDeltaJson,
      hasAttachment: var_hasAttachment,
      attachments: var_attachments,
    );
  }

  @protected
  OAuthTokenInput sse_decode_o_auth_token_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_clientId = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_expiresAtMs = sse_decode_i_64(deserializer);
    var var_tokenEndpoint = sse_decode_String(deserializer);
    var var_scopes = sse_decode_String(deserializer);
    return OAuthTokenInput(
      provider: var_provider,
      clientId: var_clientId,
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      expiresAtMs: var_expiresAtMs,
      tokenEndpoint: var_tokenEndpoint,
      scopes: var_scopes,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MessageDto? sse_decode_opt_box_autoadd_message_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_message_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutgoingMessageInput sse_decode_outgoing_message_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accountId = sse_decode_String(deserializer);
    var var_to = sse_decode_list_String(deserializer);
    var var_cc = sse_decode_list_String(deserializer);
    var var_bcc = sse_decode_list_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_plainText = sse_decode_String(deserializer);
    var var_htmlText = sse_decode_String(deserializer);
    var var_attachmentPaths = sse_decode_list_String(deserializer);
    var var_storedAttachmentIds = sse_decode_list_String(deserializer);
    var var_highImportance = sse_decode_bool(deserializer);
    return OutgoingMessageInput(
      accountId: var_accountId,
      to: var_to,
      cc: var_cc,
      bcc: var_bcc,
      subject: var_subject,
      plainText: var_plainText,
      htmlText: var_htmlText,
      attachmentPaths: var_attachmentPaths,
      storedAttachmentIds: var_storedAttachmentIds,
      highImportance: var_highImportance,
    );
  }

  @protected
  TaskDto sse_decode_task_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_dueAtMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    return TaskDto(
      id: var_id,
      title: var_title,
      dueAtMs: var_dueAtMs,
      completed: var_completed,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mailboxes = sse_decode_list_mailbox_dto(deserializer);
    var var_favoriteMailboxIds = sse_decode_list_String(deserializer);
    var var_darkModeEnabled = sse_decode_bool(deserializer);
    var var_messages = sse_decode_list_message_dto(deserializer);
    var var_calendarEvents = sse_decode_list_calendar_event_dto(deserializer);
    var var_tasks = sse_decode_list_task_dto(deserializer);
    var var_contacts = sse_decode_list_contact_dto(deserializer);
    var var_mailAccounts = sse_decode_list_mail_account_dto(deserializer);
    var var_syncWarnings = sse_decode_list_String(deserializer);
    var var_catalogMessagesRemaining = sse_decode_u_32(deserializer);
    var var_deltaMailboxesSynchronized = sse_decode_u_32(deserializer);
    var var_fullMailboxesReconciled = sse_decode_u_32(deserializer);
    var var_qresyncMailboxesSynchronized = sse_decode_u_32(deserializer);
    var var_pendingMailOperations = sse_decode_u_32(deserializer);
    return WorkspaceSnapshot(
      mailboxes: var_mailboxes,
      favoriteMailboxIds: var_favoriteMailboxIds,
      darkModeEnabled: var_darkModeEnabled,
      messages: var_messages,
      calendarEvents: var_calendarEvents,
      tasks: var_tasks,
      contacts: var_contacts,
      mailAccounts: var_mailAccounts,
      syncWarnings: var_syncWarnings,
      catalogMessagesRemaining: var_catalogMessagesRemaining,
      deltaMailboxesSynchronized: var_deltaMailboxesSynchronized,
      fullMailboxesReconciled: var_fullMailboxesReconciled,
      qresyncMailboxesSynchronized: var_qresyncMailboxesSynchronized,
      pendingMailOperations: var_pendingMailOperations,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_calendar_event_input(
    LocalCalendarEventInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_calendar_event_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_contact_input(
    LocalContactInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_contact_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_message_input(
    LocalMessageInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_message_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_task_input(
    LocalTaskInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_task_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mail_account_input(
    MailAccountInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mail_account_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_message_dto(
    MessageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_o_auth_token_input(
    OAuthTokenInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_o_auth_token_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_outgoing_message_input(
    OutgoingMessageInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_outgoing_message_input(self, serializer);
  }

  @protected
  void sse_encode_calendar_event_dto(
    CalendarEventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.startsAtMs, serializer);
    sse_encode_i_64(self.endsAtMs, serializer);
    sse_encode_opt_String(self.location, serializer);
  }

  @protected
  void sse_encode_contact_dto(ContactDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.email, serializer);
  }

  @protected
  void sse_encode_draft_sync_dto(DraftSyncDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.synchronized, serializer);
    sse_encode_u_32(self.pending, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_calendar_event_dto(
    List<CalendarEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_calendar_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_contact_dto(
    List<ContactDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_contact_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mail_account_dto(
    List<MailAccountDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mail_account_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mailbox_dto(
    List<MailboxDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mailbox_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_attachment_dto(
    List<MessageAttachmentDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_attachment_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_dto(List<TaskDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_local_calendar_event_input(
    LocalCalendarEventInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.startsAtMs, serializer);
    sse_encode_i_64(self.endsAtMs, serializer);
    sse_encode_opt_String(self.location, serializer);
  }

  @protected
  void sse_encode_local_contact_input(
    LocalContactInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.email, serializer);
  }

  @protected
  void sse_encode_local_message_input(
    LocalMessageInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.accountId, serializer);
    sse_encode_String(self.mailboxId, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.preview, serializer);
    sse_encode_String(self.plainText, serializer);
    sse_encode_String(self.htmlText, serializer);
    sse_encode_list_String(self.attachmentPaths, serializer);
    sse_encode_list_String(self.retainedAttachmentIds, serializer);
    sse_encode_String(self.draftTo, serializer);
    sse_encode_String(self.draftCc, serializer);
    sse_encode_String(self.draftBcc, serializer);
    sse_encode_String(self.editorDeltaJson, serializer);
    sse_encode_i_64(self.receivedAtMs, serializer);
    sse_encode_bool(self.unread, serializer);
    sse_encode_bool(self.flagged, serializer);
    sse_encode_bool(self.draft, serializer);
    sse_encode_bool(self.hasAttachment, serializer);
  }

  @protected
  void sse_encode_local_task_input(
    LocalTaskInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueAtMs, serializer);
    sse_encode_bool(self.completed, serializer);
  }

  @protected
  void sse_encode_mail_account_dto(
    MailAccountDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.imapHost, serializer);
    sse_encode_u_16(self.imapPort, serializer);
    sse_encode_String(self.imapSecurity, serializer);
    sse_encode_String(self.imapUsername, serializer);
    sse_encode_String(self.smtpHost, serializer);
    sse_encode_u_16(self.smtpPort, serializer);
    sse_encode_String(self.smtpSecurity, serializer);
    sse_encode_String(self.smtpUsername, serializer);
    sse_encode_String(self.authentication, serializer);
    sse_encode_opt_String(self.oauthProvider, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSyncAtMs, serializer);
  }

  @protected
  void sse_encode_mail_account_input(
    MailAccountInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.imapHost, serializer);
    sse_encode_u_16(self.imapPort, serializer);
    sse_encode_String(self.imapSecurity, serializer);
    sse_encode_String(self.imapUsername, serializer);
    sse_encode_String(self.smtpHost, serializer);
    sse_encode_u_16(self.smtpPort, serializer);
    sse_encode_String(self.smtpSecurity, serializer);
    sse_encode_String(self.smtpUsername, serializer);
  }

  @protected
  void sse_encode_mailbox_dto(MailboxDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.accountId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_u_32(self.unreadCount, serializer);
    sse_encode_u_32(self.totalCount, serializer);
  }

  @protected
  void sse_encode_mailbox_idle_dto(
    MailboxIdleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.idleSupported, serializer);
    sse_encode_bool(self.changed, serializer);
  }

  @protected
  void sse_encode_message_attachment_dto(
    MessageAttachmentDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_u_32(self.sizeBytes, serializer);
    sse_encode_bool(self.availableLocally, serializer);
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.accountId, serializer);
    sse_encode_String(self.mailboxId, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.preview, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.plainText, serializer);
    sse_encode_i_64(self.receivedAtMs, serializer);
    sse_encode_bool(self.unread, serializer);
    sse_encode_bool(self.flagged, serializer);
    sse_encode_bool(self.draft, serializer);
    sse_encode_bool(self.editableDraft, serializer);
    sse_encode_bool(self.draftSynchronized, serializer);
    sse_encode_String(self.draftTo, serializer);
    sse_encode_String(self.draftCc, serializer);
    sse_encode_String(self.draftBcc, serializer);
    sse_encode_String(self.toRecipients, serializer);
    sse_encode_String(self.ccRecipients, serializer);
    sse_encode_String(self.bccRecipients, serializer);
    sse_encode_String(self.editorDeltaJson, serializer);
    sse_encode_bool(self.hasAttachment, serializer);
    sse_encode_list_message_attachment_dto(self.attachments, serializer);
  }

  @protected
  void sse_encode_o_auth_token_input(
    OAuthTokenInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.clientId, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_i_64(self.expiresAtMs, serializer);
    sse_encode_String(self.tokenEndpoint, serializer);
    sse_encode_String(self.scopes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_message_dto(
    MessageDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_message_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_outgoing_message_input(
    OutgoingMessageInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accountId, serializer);
    sse_encode_list_String(self.to, serializer);
    sse_encode_list_String(self.cc, serializer);
    sse_encode_list_String(self.bcc, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.plainText, serializer);
    sse_encode_String(self.htmlText, serializer);
    sse_encode_list_String(self.attachmentPaths, serializer);
    sse_encode_list_String(self.storedAttachmentIds, serializer);
    sse_encode_bool(self.highImportance, serializer);
  }

  @protected
  void sse_encode_task_dto(TaskDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueAtMs, serializer);
    sse_encode_bool(self.completed, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_mailbox_dto(self.mailboxes, serializer);
    sse_encode_list_String(self.favoriteMailboxIds, serializer);
    sse_encode_bool(self.darkModeEnabled, serializer);
    sse_encode_list_message_dto(self.messages, serializer);
    sse_encode_list_calendar_event_dto(self.calendarEvents, serializer);
    sse_encode_list_task_dto(self.tasks, serializer);
    sse_encode_list_contact_dto(self.contacts, serializer);
    sse_encode_list_mail_account_dto(self.mailAccounts, serializer);
    sse_encode_list_String(self.syncWarnings, serializer);
    sse_encode_u_32(self.catalogMessagesRemaining, serializer);
    sse_encode_u_32(self.deltaMailboxesSynchronized, serializer);
    sse_encode_u_32(self.fullMailboxesReconciled, serializer);
    sse_encode_u_32(self.qresyncMailboxesSynchronized, serializer);
    sse_encode_u_32(self.pendingMailOperations, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
