// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/workspace.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LocalCalendarEventInput dco_decode_box_autoadd_local_calendar_event_input(
    dynamic raw,
  );

  @protected
  LocalContactInput dco_decode_box_autoadd_local_contact_input(dynamic raw);

  @protected
  LocalMessageInput dco_decode_box_autoadd_local_message_input(dynamic raw);

  @protected
  LocalTaskInput dco_decode_box_autoadd_local_task_input(dynamic raw);

  @protected
  MailAccountInput dco_decode_box_autoadd_mail_account_input(dynamic raw);

  @protected
  MessageDto dco_decode_box_autoadd_message_dto(dynamic raw);

  @protected
  OAuthTokenInput dco_decode_box_autoadd_o_auth_token_input(dynamic raw);

  @protected
  OutgoingMessageInput dco_decode_box_autoadd_outgoing_message_input(
    dynamic raw,
  );

  @protected
  CalendarEventDto dco_decode_calendar_event_dto(dynamic raw);

  @protected
  ContactDto dco_decode_contact_dto(dynamic raw);

  @protected
  DraftSyncDto dco_decode_draft_sync_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CalendarEventDto> dco_decode_list_calendar_event_dto(dynamic raw);

  @protected
  List<ContactDto> dco_decode_list_contact_dto(dynamic raw);

  @protected
  List<MailAccountDto> dco_decode_list_mail_account_dto(dynamic raw);

  @protected
  List<MailboxDto> dco_decode_list_mailbox_dto(dynamic raw);

  @protected
  List<MessageAttachmentDto> dco_decode_list_message_attachment_dto(
    dynamic raw,
  );

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TaskDto> dco_decode_list_task_dto(dynamic raw);

  @protected
  LocalCalendarEventInput dco_decode_local_calendar_event_input(dynamic raw);

  @protected
  LocalContactInput dco_decode_local_contact_input(dynamic raw);

  @protected
  LocalMessageInput dco_decode_local_message_input(dynamic raw);

  @protected
  LocalTaskInput dco_decode_local_task_input(dynamic raw);

  @protected
  MailAccountDto dco_decode_mail_account_dto(dynamic raw);

  @protected
  MailAccountInput dco_decode_mail_account_input(dynamic raw);

  @protected
  MailboxDto dco_decode_mailbox_dto(dynamic raw);

  @protected
  MailboxIdleDto dco_decode_mailbox_idle_dto(dynamic raw);

  @protected
  MessageAttachmentDto dco_decode_message_attachment_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  OAuthTokenInput dco_decode_o_auth_token_input(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MessageDto? dco_decode_opt_box_autoadd_message_dto(dynamic raw);

  @protected
  OutgoingMessageInput dco_decode_outgoing_message_input(dynamic raw);

  @protected
  TaskDto dco_decode_task_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceSnapshot dco_decode_workspace_snapshot(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LocalCalendarEventInput sse_decode_box_autoadd_local_calendar_event_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalContactInput sse_decode_box_autoadd_local_contact_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalMessageInput sse_decode_box_autoadd_local_message_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalTaskInput sse_decode_box_autoadd_local_task_input(
    SseDeserializer deserializer,
  );

  @protected
  MailAccountInput sse_decode_box_autoadd_mail_account_input(
    SseDeserializer deserializer,
  );

  @protected
  MessageDto sse_decode_box_autoadd_message_dto(SseDeserializer deserializer);

  @protected
  OAuthTokenInput sse_decode_box_autoadd_o_auth_token_input(
    SseDeserializer deserializer,
  );

  @protected
  OutgoingMessageInput sse_decode_box_autoadd_outgoing_message_input(
    SseDeserializer deserializer,
  );

  @protected
  CalendarEventDto sse_decode_calendar_event_dto(SseDeserializer deserializer);

  @protected
  ContactDto sse_decode_contact_dto(SseDeserializer deserializer);

  @protected
  DraftSyncDto sse_decode_draft_sync_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CalendarEventDto> sse_decode_list_calendar_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ContactDto> sse_decode_list_contact_dto(SseDeserializer deserializer);

  @protected
  List<MailAccountDto> sse_decode_list_mail_account_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MailboxDto> sse_decode_list_mailbox_dto(SseDeserializer deserializer);

  @protected
  List<MessageAttachmentDto> sse_decode_list_message_attachment_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TaskDto> sse_decode_list_task_dto(SseDeserializer deserializer);

  @protected
  LocalCalendarEventInput sse_decode_local_calendar_event_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalContactInput sse_decode_local_contact_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalMessageInput sse_decode_local_message_input(
    SseDeserializer deserializer,
  );

  @protected
  LocalTaskInput sse_decode_local_task_input(SseDeserializer deserializer);

  @protected
  MailAccountDto sse_decode_mail_account_dto(SseDeserializer deserializer);

  @protected
  MailAccountInput sse_decode_mail_account_input(SseDeserializer deserializer);

  @protected
  MailboxDto sse_decode_mailbox_dto(SseDeserializer deserializer);

  @protected
  MailboxIdleDto sse_decode_mailbox_idle_dto(SseDeserializer deserializer);

  @protected
  MessageAttachmentDto sse_decode_message_attachment_dto(
    SseDeserializer deserializer,
  );

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  OAuthTokenInput sse_decode_o_auth_token_input(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MessageDto? sse_decode_opt_box_autoadd_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  OutgoingMessageInput sse_decode_outgoing_message_input(
    SseDeserializer deserializer,
  );

  @protected
  TaskDto sse_decode_task_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceSnapshot sse_decode_workspace_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_calendar_event_input(
    LocalCalendarEventInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_contact_input(
    LocalContactInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_message_input(
    LocalMessageInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_task_input(
    LocalTaskInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mail_account_input(
    MailAccountInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_dto(
    MessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_o_auth_token_input(
    OAuthTokenInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outgoing_message_input(
    OutgoingMessageInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_calendar_event_dto(
    CalendarEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_dto(ContactDto self, SseSerializer serializer);

  @protected
  void sse_encode_draft_sync_dto(DraftSyncDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_calendar_event_dto(
    List<CalendarEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_contact_dto(
    List<ContactDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mail_account_dto(
    List<MailAccountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mailbox_dto(
    List<MailboxDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_attachment_dto(
    List<MessageAttachmentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_dto(List<TaskDto> self, SseSerializer serializer);

  @protected
  void sse_encode_local_calendar_event_input(
    LocalCalendarEventInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_contact_input(
    LocalContactInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_message_input(
    LocalMessageInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_task_input(
    LocalTaskInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mail_account_dto(
    MailAccountDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mail_account_input(
    MailAccountInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mailbox_dto(MailboxDto self, SseSerializer serializer);

  @protected
  void sse_encode_mailbox_idle_dto(
    MailboxIdleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_attachment_dto(
    MessageAttachmentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_o_auth_token_input(
    OAuthTokenInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_dto(
    MessageDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outgoing_message_input(
    OutgoingMessageInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_dto(TaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_snapshot(
    WorkspaceSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
