// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attachment_content_type`, `attachment_object_path`, `cache_remote_message`, `calendar_event_dto`, `cleanup_import_backups`, `compact_preview`, `connector_credential`, `contact_dto`, `copy_local_attachment`, `current_timestamp_ms`, `draft_recipient_list`, `imap_identities`, `import_backup_path`, `install_staged_profile`, `load_account_credential`, `load_outgoing_attachments`, `load_snapshot`, `load_stored_outgoing_attachments`, `mail_account_dto`, `mail_account_from_input`, `mail_provider_name`, `mailbox_dto`, `mailbox_role_name`, `message_dto`, `message_dtos`, `migrate_legacy_credentials`, `oauth_access_token`, `open_profile_store`, `parse_mail_provider`, `parse_transport_security`, `persist_attachment_objects`, `plain_text_as_html`, `profile_object_root`, `profile_vault`, `prototype_body`, `prototype_mailbox`, `prototype_messages`, `remote_mailbox_id`, `remote_message_id`, `remove_attachment_objects`, `remove_oauth_secrets`, `replace_cached_vault`, `required_secret`, `rollback_imported_profile`, `seed_prototype`, `synchronize_account`, `synchronize_graph_account`, `synchronize_imap_account`, `synchronize_pending_drafts`, `synchronized_draft_ids`, `task_dto`, `transport_security_name`, `upgrade_prototype_content`, `validate_combined_outgoing_attachments`, `validate_draft_metadata`, `validate_oauth_provider_for_account`, `validate_oauth_token_endpoint`, `validate_oauth_token_input`, `validate_outgoing_attachment_set`, `validated_display_name`, `validated_server_name`, `validated_text`, `write_exported_attachment`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountSyncReport`, `CachedRemoteInput`, `PendingDraftUpload`, `RemoteAttachmentDescriptor`, `StoredMailCredential`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

/// Opens the local profile database and returns its mail workspace snapshot.
///
/// The first prototype run seeds deterministic local sample data. Subsequent
/// launches read the same persisted records from SQLite.
///
/// # Errors
///
/// Returns a user-presentable description when the profile database cannot be
/// opened, migrated, seeded, or read.
Future<WorkspaceSnapshot> openWorkspace({required String databasePath}) =>
    RustLib.instance.api.crateApiWorkspaceOpenWorkspace(
      databasePath: databasePath,
    );

/// Searches mail metadata or the broader locally cached content inside the
/// encrypted profile.
///
/// The default scope covers subject, sender, address, and all retained
/// recipients. When `include_content` is true it additionally covers preview,
/// cached body text, and attachment names. The encrypted FTS index returns
/// field-weighted matches without exposing terms or indexed text outside the
/// profile.
///
/// # Errors
///
/// Returns an error when the query is excessive or the encrypted index cannot
/// be read.
Future<List<MessageDto>> searchProfileMessages({
  required String databasePath,
  required String query,
  required bool includeContent,
  required int limit,
}) => RustLib.instance.api.crateApiWorkspaceSearchProfileMessages(
  databasePath: databasePath,
  query: query,
  includeContent: includeContent,
  limit: limit,
);

/// Loads one bounded page from an already encrypted local mailbox catalogue.
///
/// This never performs network I/O. Header-only entries are returned with an
/// empty body and can be populated on demand through
/// [`load_remote_message_content`].
///
/// # Errors
///
/// Returns a validation or encrypted-profile storage error.
Future<List<MessageDto>> loadMailboxMessages({
  required String databasePath,
  required String mailboxId,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiWorkspaceLoadMailboxMessages(
  databasePath: databasePath,
  mailboxId: mailboxId,
  offset: offset,
  limit: limit,
);

/// Persists a locally composed message and its body atomically.
///
/// # Errors
///
/// Returns a user-presentable description when identifiers, the sender
/// address, or the storage transaction are invalid.
Future<MessageDto> saveLocalMessage({
  required String databasePath,
  required LocalMessageInput input,
}) => RustLib.instance.api.crateApiWorkspaceSaveLocalMessage(
  databasePath: databasePath,
  input: input,
);

/// Downloads and stores the bounded display body for one header-only remote
/// search result.
///
/// # Errors
///
/// Returns an error when the remote identity is stale, the account credential
/// is unavailable, or the bounded IMAP body download cannot be persisted.
Future<MessageDto?> loadRemoteMessageContent({
  required String databasePath,
  required String messageId,
}) => RustLib.instance.api.crateApiWorkspaceLoadRemoteMessageContent(
  databasePath: databasePath,
  messageId: messageId,
);

/// Waits for a push-style IMAP IDLE notification on one configured mailbox.
///
/// The call is bounded by `timeout_seconds`. If the server lacks QRESYNC, a
/// received IDLE notification marks only this mailbox for a full UID safety
/// reconciliation during the immediately following synchronization.
///
/// # Errors
///
/// Returns an account, credential, connection, or protocol error. Local and
/// virtual folders return an unsupported result without opening a connection.
Future<MailboxIdleDto> waitForMailboxIdleChange({
  required String databasePath,
  required String mailboxId,
  required int timeoutSeconds,
}) => RustLib.instance.api.crateApiWorkspaceWaitForMailboxIdleChange(
  databasePath: databasePath,
  mailboxId: mailboxId,
  timeoutSeconds: timeoutSeconds,
);

/// Saves one cached or server-backed attachment to a user-selected destination.
///
/// # Errors
///
/// Returns an error when metadata is unknown or stale, the local object is
/// invalid, the server download cannot be verified, or the destination cannot
/// be written. Server-backed sections are fetched with IMAP `BODY.PEEK`.
Future<void> exportAttachment({
  required String databasePath,
  required String attachmentId,
  required String destinationPath,
}) => RustLib.instance.api.crateApiWorkspaceExportAttachment(
  databasePath: databasePath,
  attachmentId: attachmentId,
  destinationPath: destinationPath,
);

/// Writes a complete password-protected profile backup.
///
/// The archive contains the already encrypted database, encrypted local
/// objects, and account credentials. Its profile key is wrapped with an
/// Argon2id-derived export key; the password itself is never stored.
///
/// # Errors
///
/// Returns an error when the profile cannot be checkpointed, an object is
/// unsafe, the password is too short, or the destination cannot be written.
Future<void> exportProfile({
  required String databasePath,
  required String destinationPath,
  required String password,
}) => RustLib.instance.api.crateApiWorkspaceExportProfile(
  databasePath: databasePath,
  destinationPath: destinationPath,
  password: password,
);

/// Replaces the active local profile with an authenticated portable backup.
///
/// Import first extracts and validates the encrypted database in a staging
/// directory. Existing local data is retained until the replacement and new
/// OS-protected profile key have both been installed.
///
/// # Errors
///
/// Returns an error for a wrong password, a modified archive, an invalid
/// database key, or a failed atomic replacement.
Future<WorkspaceSnapshot> importProfile({
  required String databasePath,
  required String sourcePath,
  required String password,
}) => RustLib.instance.api.crateApiWorkspaceImportProfile(
  databasePath: databasePath,
  sourcePath: sourcePath,
  password: password,
);

/// Persists mailbox placement and user-controlled flags for one message.
///
/// # Errors
///
/// Returns a user-presentable description when identifiers are invalid, the
/// message is missing, or the transaction fails.
Future<int> updateLocalMessage({
  required String databasePath,
  required String messageId,
  required String mailboxId,
  required bool unread,
  required bool flagged,
}) => RustLib.instance.api.crateApiWorkspaceUpdateLocalMessage(
  databasePath: databasePath,
  messageId: messageId,
  mailboxId: mailboxId,
  unread: unread,
  flagged: flagged,
);

/// Creates a user-defined local mailbox.
///
/// # Errors
///
/// Returns a user-presentable description when the identifier, display name,
/// or storage transaction is invalid.
Future<void> createLocalMailbox({
  required String databasePath,
  required String mailboxId,
  required String displayName,
}) => RustLib.instance.api.crateApiWorkspaceCreateLocalMailbox(
  databasePath: databasePath,
  mailboxId: mailboxId,
  displayName: displayName,
);

/// Renames one locally stored mailbox.
///
/// # Errors
///
/// Returns a user-presentable description when the identifier, display name,
/// or storage operation is invalid.
Future<void> renameLocalMailbox({
  required String databasePath,
  required String mailboxId,
  required String displayName,
}) => RustLib.instance.api.crateApiWorkspaceRenameLocalMailbox(
  databasePath: databasePath,
  mailboxId: mailboxId,
  displayName: displayName,
);

/// Deletes a custom mailbox and moves its contents to the fallback mailbox.
///
/// # Errors
///
/// Returns a user-presentable description when identifiers are invalid, the
/// target is not a custom mailbox, or the transaction fails.
Future<void> deleteLocalMailbox({
  required String databasePath,
  required String mailboxId,
  required String fallbackMailboxId,
}) => RustLib.instance.api.crateApiWorkspaceDeleteLocalMailbox(
  databasePath: databasePath,
  mailboxId: mailboxId,
  fallbackMailboxId: fallbackMailboxId,
);

/// Replaces the ordered favorite-mailbox list stored in the encrypted profile.
/// The exact mailbox identifiers remain provider-independent local keys.
///
/// # Errors
///
/// Returns an error when an identifier is invalid, duplicated, unknown, or
/// the encrypted preference cannot be committed.
Future<void> saveFavoriteMailboxes({
  required String databasePath,
  required List<String> mailboxIds,
}) => RustLib.instance.api.crateApiWorkspaceSaveFavoriteMailboxes(
  databasePath: databasePath,
  mailboxIds: mailboxIds,
);

/// Replaces the set of collapsed folder subtrees stored in the encrypted
/// profile.
///
/// # Errors
///
/// Returns an error when an identifier is invalid or duplicated, or the
/// encrypted preference cannot be committed.
Future<void> saveCollapsedMailboxes({
  required String databasePath,
  required List<String> mailboxIds,
}) => RustLib.instance.api.crateApiWorkspaceSaveCollapsedMailboxes(
  databasePath: databasePath,
  mailboxIds: mailboxIds,
);

/// Persists the selected light or dark desktop color scheme in the encrypted
/// profile.
///
/// # Errors
///
/// Returns an error when the profile cannot be opened or updated.
Future<void> saveDarkMode({
  required String databasePath,
  required bool enabled,
}) => RustLib.instance.api.crateApiWorkspaceSaveDarkMode(
  databasePath: databasePath,
  enabled: enabled,
);

/// Creates or updates a local calendar event.
///
/// # Errors
///
/// Returns a validation or storage error when the event cannot be committed.
Future<void> saveLocalCalendarEvent({
  required String databasePath,
  required LocalCalendarEventInput input,
}) => RustLib.instance.api.crateApiWorkspaceSaveLocalCalendarEvent(
  databasePath: databasePath,
  input: input,
);

/// Creates or updates a local task.
///
/// # Errors
///
/// Returns a validation or storage error when the task cannot be committed.
Future<void> saveLocalTask({
  required String databasePath,
  required LocalTaskInput input,
}) => RustLib.instance.api.crateApiWorkspaceSaveLocalTask(
  databasePath: databasePath,
  input: input,
);

/// Creates or updates a local contact.
///
/// # Errors
///
/// Returns a validation or storage error when the contact cannot be committed.
Future<void> saveLocalContact({
  required String databasePath,
  required LocalContactInput input,
}) => RustLib.instance.api.crateApiWorkspaceSaveLocalContact(
  databasePath: databasePath,
  input: input,
);

/// Saves account configuration and places its password inside the encrypted
/// profile vault.
///
/// # Errors
///
/// Returns a validation or encrypted-profile error. Passwords are never
/// included in workspace snapshots.
Future<void> saveMailAccount({
  required String databasePath,
  required MailAccountInput input,
  required String password,
}) => RustLib.instance.api.crateApiWorkspaceSaveMailAccount(
  databasePath: databasePath,
  input: input,
  password: password,
);

/// Saves an OAuth-backed IMAP/SMTP account and its refreshable token set in
/// the encrypted profile vault.
///
/// Native applications must use Authorization Code + PKCE and must not ship a
/// client secret. The refresh token never crosses back into Flutter snapshots.
Future<void> saveOauthMailAccount({
  required String databasePath,
  required MailAccountInput input,
  required OAuthTokenInput tokens,
}) => RustLib.instance.api.crateApiWorkspaceSaveOauthMailAccount(
  databasePath: databasePath,
  input: input,
  tokens: tokens,
);

/// Deletes an account, its cached mail, and its vault credential.
///
/// Calendar entries, tasks, contacts, and other accounts are not affected.
///
/// # Errors
///
/// Returns an account lookup or encrypted-profile storage error.
Future<WorkspaceSnapshot> deleteMailAccount({
  required String databasePath,
  required String accountId,
}) => RustLib.instance.api.crateApiWorkspaceDeleteMailAccount(
  databasePath: databasePath,
  accountId: accountId,
);

/// Tests IMAP login and SMTP submission connectivity without persisting the
/// supplied configuration or sending a message.
///
/// # Errors
///
/// Returns a validation, TLS, authentication, or protocol error.
Future<void> testMailAccountConnection({
  required MailAccountInput input,
  required String password,
}) => RustLib.instance.api.crateApiWorkspaceTestMailAccountConnection(
  input: input,
  password: password,
);

/// Tests IMAP and SMTP with a short-lived OAuth access token without storing
/// either the configuration or token.
Future<void> testOauthMailAccountConnection({
  required MailAccountInput input,
  required String accessToken,
}) => RustLib.instance.api.crateApiWorkspaceTestOauthMailAccountConnection(
  input: input,
  accessToken: accessToken,
);

/// Pushes queued draft creates, edits, and removals for one account without
/// running a full mailbox catalogue pass.
///
/// # Errors
///
/// Returns an account, credential, connection, protocol, or storage error.
Future<DraftSyncDto> synchronizeMailAccountDrafts({
  required String databasePath,
  required String accountId,
}) => RustLib.instance.api.crateApiWorkspaceSynchronizeMailAccountDrafts(
  databasePath: databasePath,
  accountId: accountId,
);

/// Progressively catalogues compact message metadata, synchronizes a bounded
/// set of recent bodies for every configured account, and returns a refreshed
/// local snapshot.
///
/// # Errors
///
/// Returns a credential, network, MIME, or storage error. Existing cached data
/// remains available when synchronization fails.
Future<WorkspaceSnapshot> synchronizeMailAccounts({
  required String databasePath,
}) => RustLib.instance.api.crateApiWorkspaceSynchronizeMailAccounts(
  databasePath: databasePath,
);

/// Sends a multipart HTML message with a plain-text alternative and validated
/// user-selected attachments through one configured SMTP account.
///
/// # Errors
///
/// Returns an account lookup, credential, address, connection, or SMTP error.
Future<String> sendAccountMessage({
  required String databasePath,
  required OutgoingMessageInput input,
}) => RustLib.instance.api.crateApiWorkspaceSendAccountMessage(
  databasePath: databasePath,
  input: input,
);

class CalendarEventDto {
  final String id;
  final String title;
  final PlatformInt64 startsAtMs;
  final PlatformInt64 endsAtMs;
  final String? location;

  const CalendarEventDto({
    required this.id,
    required this.title,
    required this.startsAtMs,
    required this.endsAtMs,
    this.location,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startsAtMs.hashCode ^
      endsAtMs.hashCode ^
      location.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalendarEventDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startsAtMs == other.startsAtMs &&
          endsAtMs == other.endsAtMs &&
          location == other.location;
}

class ContactDto {
  final String id;
  final String name;
  final String email;

  const ContactDto({required this.id, required this.name, required this.email});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          email == other.email;
}

/// Result of pushing the durable draft queue for one account.
class DraftSyncDto {
  final int synchronized;
  final int pending;
  final List<String> warnings;

  const DraftSyncDto({
    required this.synchronized,
    required this.pending,
    required this.warnings,
  });

  @override
  int get hashCode =>
      synchronized.hashCode ^ pending.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftSyncDto &&
          runtimeType == other.runtimeType &&
          synchronized == other.synchronized &&
          pending == other.pending &&
          warnings == other.warnings;
}

class LocalCalendarEventInput {
  final String id;
  final String title;
  final PlatformInt64 startsAtMs;
  final PlatformInt64 endsAtMs;
  final String? location;

  const LocalCalendarEventInput({
    required this.id,
    required this.title,
    required this.startsAtMs,
    required this.endsAtMs,
    this.location,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startsAtMs.hashCode ^
      endsAtMs.hashCode ^
      location.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalCalendarEventInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startsAtMs == other.startsAtMs &&
          endsAtMs == other.endsAtMs &&
          location == other.location;
}

class LocalContactInput {
  final String id;
  final String name;
  final String email;

  const LocalContactInput({
    required this.id,
    required this.name,
    required this.email,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalContactInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          email == other.email;
}

/// User-created local message passed from the composition workflow.
class LocalMessageInput {
  final String id;
  final String accountId;
  final String mailboxId;
  final String sender;
  final String email;
  final String subject;
  final String preview;
  final String plainText;
  final String htmlText;
  final List<String> attachmentPaths;
  final List<String> retainedAttachmentIds;
  final String draftTo;
  final String draftCc;
  final String draftBcc;
  final String editorDeltaJson;
  final PlatformInt64 receivedAtMs;
  final bool unread;
  final bool flagged;
  final bool draft;
  final bool hasAttachment;

  const LocalMessageInput({
    required this.id,
    required this.accountId,
    required this.mailboxId,
    required this.sender,
    required this.email,
    required this.subject,
    required this.preview,
    required this.plainText,
    required this.htmlText,
    required this.attachmentPaths,
    required this.retainedAttachmentIds,
    required this.draftTo,
    required this.draftCc,
    required this.draftBcc,
    required this.editorDeltaJson,
    required this.receivedAtMs,
    required this.unread,
    required this.flagged,
    required this.draft,
    required this.hasAttachment,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      mailboxId.hashCode ^
      sender.hashCode ^
      email.hashCode ^
      subject.hashCode ^
      preview.hashCode ^
      plainText.hashCode ^
      htmlText.hashCode ^
      attachmentPaths.hashCode ^
      retainedAttachmentIds.hashCode ^
      draftTo.hashCode ^
      draftCc.hashCode ^
      draftBcc.hashCode ^
      editorDeltaJson.hashCode ^
      receivedAtMs.hashCode ^
      unread.hashCode ^
      flagged.hashCode ^
      draft.hashCode ^
      hasAttachment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalMessageInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          mailboxId == other.mailboxId &&
          sender == other.sender &&
          email == other.email &&
          subject == other.subject &&
          preview == other.preview &&
          plainText == other.plainText &&
          htmlText == other.htmlText &&
          attachmentPaths == other.attachmentPaths &&
          retainedAttachmentIds == other.retainedAttachmentIds &&
          draftTo == other.draftTo &&
          draftCc == other.draftCc &&
          draftBcc == other.draftBcc &&
          editorDeltaJson == other.editorDeltaJson &&
          receivedAtMs == other.receivedAtMs &&
          unread == other.unread &&
          flagged == other.flagged &&
          draft == other.draft &&
          hasAttachment == other.hasAttachment;
}

class LocalTaskInput {
  final String id;
  final String title;
  final PlatformInt64? dueAtMs;
  final bool completed;

  const LocalTaskInput({
    required this.id,
    required this.title,
    this.dueAtMs,
    required this.completed,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ dueAtMs.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalTaskInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          dueAtMs == other.dueAtMs &&
          completed == other.completed;
}

class MailAccountDto {
  final String id;

  /// `imap` for the standards connector or `microsoft_graph`.
  final String provider;
  final String displayName;
  final String email;
  final String imapHost;
  final int imapPort;
  final String imapSecurity;
  final String imapUsername;
  final String smtpHost;
  final int smtpPort;
  final String smtpSecurity;
  final String smtpUsername;
  final String authentication;
  final String? oauthProvider;
  final PlatformInt64? lastSyncAtMs;

  const MailAccountDto({
    required this.id,
    required this.provider,
    required this.displayName,
    required this.email,
    required this.imapHost,
    required this.imapPort,
    required this.imapSecurity,
    required this.imapUsername,
    required this.smtpHost,
    required this.smtpPort,
    required this.smtpSecurity,
    required this.smtpUsername,
    required this.authentication,
    this.oauthProvider,
    this.lastSyncAtMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      provider.hashCode ^
      displayName.hashCode ^
      email.hashCode ^
      imapHost.hashCode ^
      imapPort.hashCode ^
      imapSecurity.hashCode ^
      imapUsername.hashCode ^
      smtpHost.hashCode ^
      smtpPort.hashCode ^
      smtpSecurity.hashCode ^
      smtpUsername.hashCode ^
      authentication.hashCode ^
      oauthProvider.hashCode ^
      lastSyncAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MailAccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          provider == other.provider &&
          displayName == other.displayName &&
          email == other.email &&
          imapHost == other.imapHost &&
          imapPort == other.imapPort &&
          imapSecurity == other.imapSecurity &&
          imapUsername == other.imapUsername &&
          smtpHost == other.smtpHost &&
          smtpPort == other.smtpPort &&
          smtpSecurity == other.smtpSecurity &&
          smtpUsername == other.smtpUsername &&
          authentication == other.authentication &&
          oauthProvider == other.oauthProvider &&
          lastSyncAtMs == other.lastSyncAtMs;
}

/// Complete user-supplied account configuration. `password` is accepted only
/// by credential-related functions and is never included in snapshots.
///
/// `provider` selects the connector: `imap` uses the IMAP/SMTP endpoints,
/// `microsoft_graph` synchronizes through the Graph API and keeps the endpoint
/// fields only as a documented fallback description.
class MailAccountInput {
  final String id;
  final String provider;
  final String displayName;
  final String email;
  final String imapHost;
  final int imapPort;
  final String imapSecurity;
  final String imapUsername;
  final String smtpHost;
  final int smtpPort;
  final String smtpSecurity;
  final String smtpUsername;

  const MailAccountInput({
    required this.id,
    required this.provider,
    required this.displayName,
    required this.email,
    required this.imapHost,
    required this.imapPort,
    required this.imapSecurity,
    required this.imapUsername,
    required this.smtpHost,
    required this.smtpPort,
    required this.smtpSecurity,
    required this.smtpUsername,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      provider.hashCode ^
      displayName.hashCode ^
      email.hashCode ^
      imapHost.hashCode ^
      imapPort.hashCode ^
      imapSecurity.hashCode ^
      imapUsername.hashCode ^
      smtpHost.hashCode ^
      smtpPort.hashCode ^
      smtpSecurity.hashCode ^
      smtpUsername.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MailAccountInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          provider == other.provider &&
          displayName == other.displayName &&
          email == other.email &&
          imapHost == other.imapHost &&
          imapPort == other.imapPort &&
          imapSecurity == other.imapSecurity &&
          imapUsername == other.imapUsername &&
          smtpHost == other.smtpHost &&
          smtpPort == other.smtpPort &&
          smtpSecurity == other.smtpSecurity &&
          smtpUsername == other.smtpUsername;
}

/// Mailbox data transferred to the Flutter interface.
class MailboxDto {
  final String id;
  final String accountId;
  final String displayName;
  final String role;
  final int unreadCount;
  final int totalCount;

  const MailboxDto({
    required this.id,
    required this.accountId,
    required this.displayName,
    required this.role,
    required this.unreadCount,
    required this.totalCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      displayName.hashCode ^
      role.hashCode ^
      unreadCount.hashCode ^
      totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MailboxDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          displayName == other.displayName &&
          role == other.role &&
          unreadCount == other.unreadCount &&
          totalCount == other.totalCount;
}

/// Result of one bounded IMAP IDLE wait for the currently visible mailbox.
class MailboxIdleDto {
  final bool idleSupported;
  final bool changed;

  const MailboxIdleDto({required this.idleSupported, required this.changed});

  @override
  int get hashCode => idleSupported.hashCode ^ changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MailboxIdleDto &&
          runtimeType == other.runtimeType &&
          idleSupported == other.idleSupported &&
          changed == other.changed;
}

/// Downloadable attachment metadata transferred to Flutter.
class MessageAttachmentDto {
  final String id;
  final String fileName;
  final String contentType;
  final int sizeBytes;
  final bool availableLocally;

  const MessageAttachmentDto({
    required this.id,
    required this.fileName,
    required this.contentType,
    required this.sizeBytes,
    required this.availableLocally,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      fileName.hashCode ^
      contentType.hashCode ^
      sizeBytes.hashCode ^
      availableLocally.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageAttachmentDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fileName == other.fileName &&
          contentType == other.contentType &&
          sizeBytes == other.sizeBytes &&
          availableLocally == other.availableLocally;
}

/// Message data transferred to the Flutter interface.
class MessageDto {
  final String id;
  final String accountId;
  final String mailboxId;
  final String sender;
  final String email;
  final String subject;
  final String preview;
  final String body;
  final String plainText;
  final PlatformInt64 receivedAtMs;
  final bool unread;
  final bool flagged;
  final bool draft;
  final bool editableDraft;
  final bool draftSynchronized;
  final String draftTo;
  final String draftCc;
  final String draftBcc;
  final String toRecipients;
  final String ccRecipients;
  final String bccRecipients;
  final String editorDeltaJson;
  final bool hasAttachment;
  final List<MessageAttachmentDto> attachments;

  const MessageDto({
    required this.id,
    required this.accountId,
    required this.mailboxId,
    required this.sender,
    required this.email,
    required this.subject,
    required this.preview,
    required this.body,
    required this.plainText,
    required this.receivedAtMs,
    required this.unread,
    required this.flagged,
    required this.draft,
    required this.editableDraft,
    required this.draftSynchronized,
    required this.draftTo,
    required this.draftCc,
    required this.draftBcc,
    required this.toRecipients,
    required this.ccRecipients,
    required this.bccRecipients,
    required this.editorDeltaJson,
    required this.hasAttachment,
    required this.attachments,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      mailboxId.hashCode ^
      sender.hashCode ^
      email.hashCode ^
      subject.hashCode ^
      preview.hashCode ^
      body.hashCode ^
      plainText.hashCode ^
      receivedAtMs.hashCode ^
      unread.hashCode ^
      flagged.hashCode ^
      draft.hashCode ^
      editableDraft.hashCode ^
      draftSynchronized.hashCode ^
      draftTo.hashCode ^
      draftCc.hashCode ^
      draftBcc.hashCode ^
      toRecipients.hashCode ^
      ccRecipients.hashCode ^
      bccRecipients.hashCode ^
      editorDeltaJson.hashCode ^
      hasAttachment.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          mailboxId == other.mailboxId &&
          sender == other.sender &&
          email == other.email &&
          subject == other.subject &&
          preview == other.preview &&
          body == other.body &&
          plainText == other.plainText &&
          receivedAtMs == other.receivedAtMs &&
          unread == other.unread &&
          flagged == other.flagged &&
          draft == other.draft &&
          editableDraft == other.editableDraft &&
          draftSynchronized == other.draftSynchronized &&
          draftTo == other.draftTo &&
          draftCc == other.draftCc &&
          draftBcc == other.draftBcc &&
          toRecipients == other.toRecipients &&
          ccRecipients == other.ccRecipients &&
          bccRecipients == other.bccRecipients &&
          editorDeltaJson == other.editorDeltaJson &&
          hasAttachment == other.hasAttachment &&
          attachments == other.attachments;
}

/// OAuth token set returned by an Authorization Code + PKCE exchange.
/// It is accepted only by credential functions and stored in the encrypted
/// profile; tokens are never returned in workspace snapshots.
class OAuthTokenInput {
  final String provider;
  final String clientId;
  final String accessToken;
  final String refreshToken;
  final PlatformInt64 expiresAtMs;
  final String tokenEndpoint;
  final String scopes;

  const OAuthTokenInput({
    required this.provider,
    required this.clientId,
    required this.accessToken,
    required this.refreshToken,
    required this.expiresAtMs,
    required this.tokenEndpoint,
    required this.scopes,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      clientId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      expiresAtMs.hashCode ^
      tokenEndpoint.hashCode ^
      scopes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthTokenInput &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          clientId == other.clientId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          expiresAtMs == other.expiresAtMs &&
          tokenEndpoint == other.tokenEndpoint &&
          scopes == other.scopes;
}

/// Rich message submitted from the desktop composer.
class OutgoingMessageInput {
  final String accountId;
  final List<String> to;
  final List<String> cc;
  final List<String> bcc;
  final String subject;
  final String plainText;
  final String htmlText;
  final List<String> attachmentPaths;
  final List<String> storedAttachmentIds;
  final bool highImportance;

  const OutgoingMessageInput({
    required this.accountId,
    required this.to,
    required this.cc,
    required this.bcc,
    required this.subject,
    required this.plainText,
    required this.htmlText,
    required this.attachmentPaths,
    required this.storedAttachmentIds,
    required this.highImportance,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      bcc.hashCode ^
      subject.hashCode ^
      plainText.hashCode ^
      htmlText.hashCode ^
      attachmentPaths.hashCode ^
      storedAttachmentIds.hashCode ^
      highImportance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingMessageInput &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          to == other.to &&
          cc == other.cc &&
          bcc == other.bcc &&
          subject == other.subject &&
          plainText == other.plainText &&
          htmlText == other.htmlText &&
          attachmentPaths == other.attachmentPaths &&
          storedAttachmentIds == other.storedAttachmentIds &&
          highImportance == other.highImportance;
}

class TaskDto {
  final String id;
  final String title;
  final PlatformInt64? dueAtMs;
  final bool completed;

  const TaskDto({
    required this.id,
    required this.title,
    this.dueAtMs,
    required this.completed,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ dueAtMs.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          dueAtMs == other.dueAtMs &&
          completed == other.completed;
}

/// Complete initial state required by the mail workspace.
class WorkspaceSnapshot {
  final List<MailboxDto> mailboxes;
  final List<String> favoriteMailboxIds;

  /// Mailboxes whose folder subtree is collapsed in the folder pane.
  final List<String> collapsedMailboxIds;
  final bool darkModeEnabled;
  final List<MessageDto> messages;
  final List<CalendarEventDto> calendarEvents;
  final List<TaskDto> tasks;
  final List<ContactDto> contacts;
  final List<MailAccountDto> mailAccounts;
  final List<String> syncWarnings;

  /// Compact IMAP catalogue entries still scheduled for automatic
  /// continuation after the current synchronization pass.
  final int catalogMessagesRemaining;
  final int deltaMailboxesSynchronized;
  final int fullMailboxesReconciled;
  final int qresyncMailboxesSynchronized;
  final int pendingMailOperations;

  const WorkspaceSnapshot({
    required this.mailboxes,
    required this.favoriteMailboxIds,
    required this.collapsedMailboxIds,
    required this.darkModeEnabled,
    required this.messages,
    required this.calendarEvents,
    required this.tasks,
    required this.contacts,
    required this.mailAccounts,
    required this.syncWarnings,
    required this.catalogMessagesRemaining,
    required this.deltaMailboxesSynchronized,
    required this.fullMailboxesReconciled,
    required this.qresyncMailboxesSynchronized,
    required this.pendingMailOperations,
  });

  @override
  int get hashCode =>
      mailboxes.hashCode ^
      favoriteMailboxIds.hashCode ^
      collapsedMailboxIds.hashCode ^
      darkModeEnabled.hashCode ^
      messages.hashCode ^
      calendarEvents.hashCode ^
      tasks.hashCode ^
      contacts.hashCode ^
      mailAccounts.hashCode ^
      syncWarnings.hashCode ^
      catalogMessagesRemaining.hashCode ^
      deltaMailboxesSynchronized.hashCode ^
      fullMailboxesReconciled.hashCode ^
      qresyncMailboxesSynchronized.hashCode ^
      pendingMailOperations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceSnapshot &&
          runtimeType == other.runtimeType &&
          mailboxes == other.mailboxes &&
          favoriteMailboxIds == other.favoriteMailboxIds &&
          collapsedMailboxIds == other.collapsedMailboxIds &&
          darkModeEnabled == other.darkModeEnabled &&
          messages == other.messages &&
          calendarEvents == other.calendarEvents &&
          tasks == other.tasks &&
          contacts == other.contacts &&
          mailAccounts == other.mailAccounts &&
          syncWarnings == other.syncWarnings &&
          catalogMessagesRemaining == other.catalogMessagesRemaining &&
          deltaMailboxesSynchronized == other.deltaMailboxesSynchronized &&
          fullMailboxesReconciled == other.fullMailboxesReconciled &&
          qresyncMailboxesSynchronized == other.qresyncMailboxesSynchronized &&
          pendingMailOperations == other.pendingMailOperations;
}
